

CREATE TABLE IF NOT EXISTS jobtitle(year string, job_title string, total int)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE jobtitle SELECT year,job_title,COUNT(job_title) AS total FROM h1b_final GROUP BY year,job_title ORDER BY year;


2016	MARRIAGE AND FAMILY THERAPIST	2
2016	MARRIAGE AND FAMILY THERAPIST INTERN	9
2016	MARTIAL ARTS INSTRUCTOR	1
2016	MARTKET RESEARCH ANALYST AND MARKETING SPECIALIST	2
2016	MARY H CAIN DISTINGUISHED PROFESSOR	1

select * from jobtitle limit 5;
OK
jobtitle.year	jobtitle.job_title	jobtitle.total
2011	(BILINGUAL) PROGRAMMER	1
2011	|NFORMATION MANAGEMENT SPECIALIST	1
2011	[HIOX] COMMERCIAL SPECIALIST (SALES ENGINEER)	1
2011	ZONE MANAGER, OPERATIONS & ANALYSIS	1
2011	YOUTH PROGRAM COORDINATOR	4



CREATE TABLE IF NOT EXISTS jobtitlepercent(year string,job_title string, percent1 float)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';


INSERT OVERWRITE TABLE jobtitlepercent SELECT year,job_title, ROUND(((total-LAG(total)OVER(ORDER BY year))*100)/LAG(total)OVER(ORDER BY year),2) AS growthpercent FROM jobtitle GROUP BY year,job_title,total;


2016	 PROJECT MANAGERS	0.0
2016	 QA ANALYST	0.0
2016	 SHAREPOINT/SQL DEVELOPER	0.0
2016	 SOFTWARE ENGINEER	2400.0
2016	 SOFTWARE PROGRAMMER	-44.0
2016	 SR. BUSINESS INTELLIGENCE DEVELOPER	-92.86



2016	MARRIAGE AND FAMILY COUNSELOR INTERN	0.0
2016	MARRIAGE AND FAMILY THERAPIST	100.0
2016	MARRIAGE AND FAMILY THERAPIST INTERN	350.0
2016	MARTIAL ARTS INSTRUCTOR	-88.89
2016	MARTKET RESEARCH ANALYST AND MARKETING SPECIALIST	100.0
2016	MARY H CAIN DISTINGUISHED PROFESSOR	-50.0


jobtitlepercent.year	jobtitlepercent.job_title	jobtitlepercent.percent1
2011	ARCHITECT ENGINEER I	NULL
2011	ARCHITECT ASSISTANT	0.0
2011	ARCHITECT 4, SOFTWARE ARCHITECTURE	0.0
2011	ARCHITECT 2 CALIFORNIA	-50.0
2011	ARCHITECT 2	0.0


SELECT job_title, ROUND(AVG(percent1),2) AS avggrowth FROM jobtitlepercent GROUP BY job_title ORDER BY avggrowth DESC LIMIT 5;

job_title	avggrowth
PROGRAMMER ANALYST	3455918.89
SOFTWARE ENGINEER	1891016.67
COMPUTER PROGRAMMER	995847.22
SYSTEMS ANALYST	787777.78
SOFTWARE DEVELOPER	715016.67


job_title	avggrowth
PROGRAMMER ANALYST	2672582.23
COMPUTER PROGRAMMER	1176066.67
SOFTWARE ENGINEER	1124539.17
SOFTWARE DEVELOPER	715016.67
SYSTEMS ANALYST	698058.33


CREATE TABLE IF NOT EXISTS jobtitlepercent1(job_title string, percent1 float)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';



INSERT OVERWRITE TABLE jobtitlepercent1 SELECT job_title, ROUND(((total-LAG(total)OVER(ORDER BY year))*100)/LAG(total)OVER(ORDER BY year),2) AS growthpercent FROM jobtitle;


SELECT job_title,AVG(percent1) AS result FROM jobtitlepercent1 ORDER BY result DESC LIMIT 5;





CREATE TABLE IF NOT EXISTS jobtitle(year string, job_title string, total int)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE jobtitle SELECT year,job_title,COUNT(job_title) AS total FROM h1b_final GROUP BY year,job_title ORDER BY year,job_title;


CREATE TABLE IF NOT EXISTS jobtitlepercent1(job_title string, growthpercent float)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

INSERT OVERWRITE TABLE jobtitlepercent1 SELECT job_title, ROUND(((total-LAG(total)OVER(ORDER BY year))*100)/LAG(total)OVER(ORDER BY year),2) AS growthpercent FROM jobtitle;


SELECT job_title, ROUND(AVG(growthpercent),2) AS avggrowth FROM jobtitlepercent GROUP BY job_title ORDER BY avggrowth DESC LIMIT 5;

